version: '3.7'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./docker/psql/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      # - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: example
       POSTGRES_DB: example

  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_AUTO_CRETE_TOPIC_ENABLE: 'true'
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      # KAFKA_LOG_DIRS: /tmp/kafka-logs-1

  ch-server:
    image: yandex/clickhouse-server
    ports:
     - "9000:9000"
    volumes:
      - "./docker/ch/init.sql:/docker-entrypoint-initdb.d/init.sql"

  # ch-client:
  #   image: yandex/clickhouse-client
  #   command: ['--host', 'ch-server']
  #   depends_on:
  #     - ch-server
