// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: proto/logger/logger.proto

package logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTailRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetTailRequest) Reset() {
	*x = GetTailRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logger_logger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTailRequest) ProtoMessage() {}

func (x *GetTailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logger_logger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTailRequest.ProtoReflect.Descriptor instead.
func (*GetTailRequest) Descriptor() ([]byte, []int) {
	return file_proto_logger_logger_proto_rawDescGZIP(), []int{0}
}

type LogRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Msg string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *LogRow) Reset() {
	*x = LogRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_logger_logger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRow) ProtoMessage() {}

func (x *LogRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logger_logger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRow.ProtoReflect.Descriptor instead.
func (*LogRow) Descriptor() ([]byte, []int) {
	return file_proto_logger_logger_proto_rawDescGZIP(), []int{1}
}

func (x *LogRow) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *LogRow) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_logger_logger_proto protoreflect.FileDescriptor

var file_proto_logger_logger_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x2f, 0x6c,
	0x6f, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x73, 0x71, 0x6c, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x54, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x46,
	0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x52, 0x6f, 0x77, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x02, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x73, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x12, 0x65, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x61, 0x69, 0x6c, 0x12,
	0x2e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x73, 0x71, 0x6c, 0x5f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x26, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x73, 0x71, 0x6c, 0x5f, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x2e, 0x4c, 0x6f, 0x67, 0x52, 0x6f, 0x77, 0x22, 0x00, 0x30, 0x01, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x78, 0x73, 0x6d, 0x75, 0x6e,
	0x64, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x70, 0x73, 0x71, 0x6c, 0x2d, 0x65, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_logger_logger_proto_rawDescOnce sync.Once
	file_proto_logger_logger_proto_rawDescData = file_proto_logger_logger_proto_rawDesc
)

func file_proto_logger_logger_proto_rawDescGZIP() []byte {
	file_proto_logger_logger_proto_rawDescOnce.Do(func() {
		file_proto_logger_logger_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_logger_logger_proto_rawDescData)
	})
	return file_proto_logger_logger_proto_rawDescData
}

var file_proto_logger_logger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_logger_logger_proto_goTypes = []interface{}{
	(*GetTailRequest)(nil),        // 0: grpc_psql_example.proto.logger.GetTailRequest
	(*LogRow)(nil),                // 1: grpc_psql_example.proto.logger.LogRow
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_logger_logger_proto_depIdxs = []int32{
	2, // 0: grpc_psql_example.proto.logger.LogRow.ts:type_name -> google.protobuf.Timestamp
	0, // 1: grpc_psql_example.proto.logger.LoggerRepo.GetTail:input_type -> grpc_psql_example.proto.logger.GetTailRequest
	1, // 2: grpc_psql_example.proto.logger.LoggerRepo.GetTail:output_type -> grpc_psql_example.proto.logger.LogRow
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_logger_logger_proto_init() }
func file_proto_logger_logger_proto_init() {
	if File_proto_logger_logger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_logger_logger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTailRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_logger_logger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_logger_logger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logger_logger_proto_goTypes,
		DependencyIndexes: file_proto_logger_logger_proto_depIdxs,
		MessageInfos:      file_proto_logger_logger_proto_msgTypes,
	}.Build()
	File_proto_logger_logger_proto = out.File
	file_proto_logger_logger_proto_rawDesc = nil
	file_proto_logger_logger_proto_goTypes = nil
	file_proto_logger_logger_proto_depIdxs = nil
}
